version: "3.9"
services:

  app-registry:
    image: registry:2
    ports:
      - "5000:5000"
    container_name: registry-cdd
    networks:
      - inaction-network
    
  jenkins:    
    build: .
    depends_on:
      - app-registry
    ports:
      - "8080:8080"
    networks:
      - inaction-network
    container_name: jenkins-cdd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/inaction-server/jenkins_home:/var/jenkins_home
        
  sonarqube:
    image: sonarqube:latest
    depends_on:
      - jenkins
    ports:
      - "9000:9000"
    networks:
      - inaction-network
    container_name: sonarqube-cdd
    volumes:
      - /var/inaction-server/sonarqube/volumes/sonarqube-conf/:/opt/sonarqube/conf
      - /var/inaction-server/sonarqube/volumes/sonarqube-data/:/opt/sonarqube/data
      - /var/inaction-server/sonarqube/volumes/sonarqube-logs/:/opt/sonarqube/logs
      - /var/inaction-server/sonarqube/volumes/sonarqube-extensions/:/opt/sonarqube/extensions

networks:
  inaction-network:
    name: inaction-network